import { create } from 'storybook/theming/create'

const fontBase = 'Segoe UI, Helvetica Neue, system-ui, sans-serif'
const fontCode = 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace'

export const docsLightTheme = create({
  base: 'light',
  brandTitle: 'Form hooks',
  brandUrl: undefined,
  brandImage: undefined,
  brandTarget: '_self',
  colorPrimary: '#0f766e',
  colorSecondary: '#0f766e',
  appBg: '#efe8dc',
  appContentBg: '#fffdf8',
  appPreviewBg: '#f4f1ea',
  appBorderColor: '#c9c0b0',
  appBorderRadius: 8,
  fontBase,
  fontCode,
  textColor: '#14213d',
  textMutedColor: '#4a5a70',
  textInverseColor: '#fffdf8',
  barTextColor: '#2c3a52',
  barSelectedColor: '#0f766e',
  barHoverColor: '#0d9488',
  barBg: '#fffdf8',
  inputBg: '#ffffff',
  inputBorder: '#c9c0b0',
  inputTextColor: '#14213d',
  inputBorderRadius: 6,
})

export const docsDarkTheme = create({
  base: 'dark',
  brandTitle: 'Form hooks',
  brandUrl: undefined,
  brandImage: undefined,
  brandTarget: '_self',
  colorPrimary: '#5eead4',
  colorSecondary: '#2dd4bf',
  appBg: '#0c1117',
  appContentBg: '#1b2330',
  appPreviewBg: '#10151c',
  appBorderColor: '#3d4c5f',
  appBorderRadius: 8,
  fontBase,
  fontCode,
  textColor: '#e8eef6',
  textMutedColor: '#9aabc0',
  textInverseColor: '#10151c',
  barTextColor: '#c5d0dc',
  barSelectedColor: '#5eead4',
  barHoverColor: '#2dd4bf',
  barBg: '#151c26',
  inputBg: '#0f141b',
  inputBorder: '#3d4c5f',
  inputTextColor: '#e8eef6',
  inputBorderRadius: 6,
})
